### ISSUE TITLE
Wrong preview rotation when on landscape

### ISSUE THREAD

**Issue by davidmartos96** [Apparence-io/camera_awesome#100]
## Steps to Reproduce

1. Run the example app on a phone.
2. Pass `DeviceOrientation.landscapeLeft` as an argument to the `CameraAwesome` fullscreen widget.

![image](https://user-images.githubusercontent.com/22084723/120079746-a97bab80-c0b5-11eb-9ef5-1e97040c35a6.png)

## Expected results

The camera preview should have a correct rotation

## Actual results

The preview is sideways

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Android* | *Moto G5 Plus*  | *11*  |

![image](https://user-images.githubusercontent.com/22084723/120079849-24dd5d00-c0b6-11eb-9948-27de20f49a05.png)

</details>

**Comment by g-apparence** [comment]
Did you manually lock the rotation on your app?

**Comment by gangstarmn** [comment]
ios has same problem here

**Comment by davidmartos96** [comment]
> Did you manually lock the rotation on your app?

No, it's free rotation, but with the UI corner to change the rotation manually.

**Comment by davidmartos96** [comment]
> Did you manually lock the rotation on your app

I passed the orientation parameter, which under the hood lock it, but I didn't do it from outside

**Comment by WindBise** [comment]
Where can i set this orientation in 2.0.0 version?
