### ISSUE TITLE
Camera preview

### ISSUE THREAD

**Issue by jenniestrongbow** [Apparence-io/camera_awesome#103]
Simple question, how do you display a camera preview? The CameraAwesome is just black.

`CameraAwesome(
      testMode: false,
      onPermissionsResult: (bool result) { print("perm: "+result.toString()); },
      selectDefaultSize: (List<Size> availableSizes) => Size(800, 480),
      onCameraStarted: () { },
      //onOrientationChanged: (CameraOrientations newOrientation) { },
      //zoom: 0.64,
      sensor: _sensor,
      photoSize: _photoSize,
      switchFlashMode: _switchFlash,
      captureMode: _captureMode,
      orientation: DeviceOrientation.portraitUp,
      fitted: true,
    )`

Thanks

**Comment by g-apparence** [comment]
Check you have put permissions to open camera. 
See Readme
