### ISSUE TITLE
[iOS] front camera mirror error

### ISSUE THREAD

**Issue by ChokShen** [Apparence-io/camera_awesome#104]
## Steps to Reproduce

Camera mirror is wrong when I open front camera by default.But when I opened back camera firstly and then switched to front camera, everything is OK.

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Apple* | *iPhone X*  | *14.2*  |

</details>

**Comment by SmirnovM91** [comment]
I've found the solution, you have to change this line 
`[_captureConnection setVideoMirrored:(_cameraSensor == Back)];` 
to
`[_captureConnection setVideoMirrored:TRUE];`
in file `CameraPreview.m` on line 91

@dim-apparence @ChokShen please fix the bug

**Comment by SmirnovM91** [comment]
Another bug with photo, change in file `CameraPictureController.m` on line 59
from `UIImageOrientationRight` to `UIImageOrientationLeftMirrored`

**Comment by bauloc** [comment]
https://github.com/Apparence-io/camera_awesome/issues/62
I tried this way and success, tested on Android + iOS.
