### ISSUE TITLE
Infinite loading 

### ISSUE THREAD

**Issue by SardorbekR** [Apparence-io/camera_awesome#106]
## Steps to Reproduce
This is my code
```dart
final ValueNotifier<CameraFlashes> _switchFlash =
      ValueNotifier(CameraFlashes.AUTO);
  final ValueNotifier<Sensors> _sensor = ValueNotifier(Sensors.BACK);
  final ValueNotifier<CaptureModes> _captureMode =
      ValueNotifier(CaptureModes.PHOTO);

  final ValueNotifier<Size> _photoSize = ValueNotifier(const Size(1920, 1080)); //is everything ok in this line? code from example throw null exception so I had to change this line
 
CameraAwesome(
            testMode: false,
            onPermissionsResult: (bool? result) {},
            selectDefaultSize: (List<Size> availableSizes) =>
                const Size(1920, 1080),
            onCameraStarted: () {},
            onOrientationChanged: (CameraOrientations? newOrientation) {},
            sensor: _sensor,
            photoSize: _photoSize,
            switchFlashMode: _switchFlash,
            captureMode: _captureMode,
            fitted: true,
          ),
```
I just launched the camera page it just shows infinite loading, **I've allowed camera permission**

## Expected results
I expected to see camera preview

## Actual results
Infinite loading
**Log:** [_retryStartCamera] 946654524
 ...retry start camera in 2 seconds... 3 try left

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Androi* | *Emulator*  | *Android 10*  |

</details>

**Comment by g-apparence** [comment]
Some emulator doesn't work with the camera. You should try on a real device sorry.

**Comment by berkaymazlumlar** [comment]
Same issue on real device. Here is my code, is there any problem?

import 'package:camerawesome/camerawesome_plugin.dart';
import 'package:camerawesome/models/orientations.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class CameraDeneme extends StatefulWidget {
  const CameraDeneme({Key? key}) : super(key: key);

  @override
  _CameraDenemeState createState() => _CameraDenemeState();
}

class _CameraDenemeState extends State<CameraDeneme>
    with TickerProviderStateMixin {
  final ValueNotifier<CameraFlashes> _switchFlash =
      ValueNotifier(CameraFlashes.AUTO);
  final ValueNotifier<Sensors> _sensor = ValueNotifier(Sensors.BACK);
  final ValueNotifier<CaptureModes> _captureMode =
      ValueNotifier(CaptureModes.PHOTO);

  final ValueNotifier<Size> _photoSize = ValueNotifier(const Size(1920, 1080));
  @override
  Widget build(BuildContext context) {
    return CameraAwesome(
      testMode: false,
      onPermissionsResult: (bool? result) {},
      selectDefaultSize: (List<Size> availableSizes) => const Size(1920, 1080),
      onCameraStarted: () {},
      onOrientationChanged: (CameraOrientations? newOrientation) {},
      sensor: _sensor,
      photoSize: _photoSize,
      switchFlashMode: _switchFlash,
      captureMode: _captureMode,
      fitted: true,
    );
  }
}

**Comment by Sreeharikr** [comment]
I have the same issue. My device is Xiaomi Redmi note 7

**Comment by apalala-dev** [comment]
This issue is rather old, please open a new one with more details (camerawesome version, details on the phone, example code, wether it happens all the time... All things that might help reproduce the problem 👌)
