### ISSUE TITLE
Warning for deprecated API on CameraSession.java

### ISSUE THREAD

**Issue by vietstone-ng** [Apparence-io/camera_awesome#107]
## Steps to Reproduce

Install the package as documentation.

## Expected results

Code runs with on warning.

## Actual results

There's a warning about deprecated API

```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/vietstone-ng/.pub-cache/hosted/pub.dartlang.org/camerawesome-0.3.0+1/android/src/main/java/com/apparence/camerawesome/CameraSession.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
|*Samsung*|    *J4+*    |*Android 9*|

</details>

**Comment by g-apparence** [comment]
This should be fixed with the reworked version #150
