### ISSUE TITLE
Camera Does not start on first Launch

### ISSUE THREAD

**Issue by pkofcgit** [Apparence-io/camera_awesome#108]
Exception has occurred.
PlatformException (PlatformException(CAMERA_MUST_BE_INIT, init must be call before start, , null))
Device :Samsung GalaxyA32, Mi Note 7
Android Version 11

the Exception is occure only first time, White Preview screen and with null text no camera is shown, its working fine after close and and restart

if i uninstall application and launch again same thing, its only happened first time

**Comment by billbull21** [comment]
in my case this problem came out because my app doesn't have a access to write storage properly.
i think that was a bug from this plugin. but, you can escape from this bug by asking to system to access the storage "BEFORE" launch the camera.

try using package permission_handler to ask permission

**Comment by lcm1475** [comment]
I have the same problem

Camera permission and cache read / write permission have been allowed before entering the camera page

However, this error still occurs after entering the camera interface for the first time

When I click back (I don't need to exit the app) to enter this page for the second time, everything is normal

**Comment by SmirnovM91** [comment]
+1
