### ISSUE TITLE
在使用相机时与动画产生冲突

### ISSUE THREAD

**Issue by 4677-li** [Apparence-io/camera_awesome#109]
## Steps to Reproduce

*Describe how to reproduce the error*

## Expected results

*What it should be*

## Actual results

*What you see*

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Apple* | *iPhone X*  | *13.6.1*  |

</details>

**Comment by g-apparence** [comment]
Please speak english
