### ISSUE TITLE
Camera preview wont start at another page

### ISSUE THREAD

**Issue by chunhtp** [Apparence-io/camera_awesome#110]
Hi,
So I got 2 different layout with take photo. 
User take the first picture at first photo layout and navigate to preview the picture, and then navigate to second take photo layout.  
Why the second take photo layout camera cant be load up ?

**Comment by chunhtp** [comment]
Thanks for the reply 
What do you mean stop and hide the camera ?

**Comment by samuelkanyi** [comment]
I am also experiencing this issue. Any workaround

**Comment by g-apparence** [comment]
This should be fixed with the reworked version #150
