### ISSUE TITLE
Camera crash on android 11 first launch

### ISSUE THREAD

**Issue by billbull21** [Apparence-io/camera_awesome#112]
## Steps to Reproduce

launch the app, open camera. they will asked some permissions. and then, the app will frezee.
i found the problem is, but i can't solve it for now.
on camerapreview.dart there was a function initPlatfromState(),

inside the function.. there is some line that make it crash.
if (Platform.isAndroid) {
      _permissionStreamSub =
          CamerawesomePlugin.listenPermissionResult()!.listen((res) {
        if (res) {
          // initPlatformState();
        }
        if (widget.onPermissionsResult != null) {
          widget.onPermissionsResult!(res);
        }
      });
    }
it will make a forever loop until the app was crashed.

## Expected results

open the camera, preview the camera

## Actual results

the app is not responding (frezee)

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Xiaomi* | *Redmi note 8 pro*  | *11*  |

</details>

**Comment by billbull21** [comment]
on android 11 it only allow permission for once or while in use. there is no option to forever allow.
i found it when my device was upgrade to android 11.

**Comment by g-apparence** [comment]
Fixed
