### ISSUE TITLE
The photo size is different from camera preview

### ISSUE THREAD

**Issue by italoDiBastos** [Apparence-io/camera_awesome#115]
## Steps to Reproduce

*Set the photo 3.264x2.448, but the camera preview is in aspect ratio 9:16*

## Expected results

*The photo in preview size*

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Samsung* | *A-10S*  | *Android 11*  |

</details>

**Comment by g-apparence** [comment]
You can now choose the preview size correctly from the builder of the new version 1.0.0
By default it's on cover mode. 

Don't hesitate to open another issue if you need any help.
