### ISSUE TITLE
Not getting the biggest resolution

### ISSUE THREAD

**Issue by ricardochen** [Apparence-io/camera_awesome#116]
## Steps to Reproduce
Copy pasted your example, selected the highest resolution (3840/2160)

flutter: ValueNotifier<Size>#36c6f(Size(3840.0, 2160.0))
flutter: ----------------------------------
flutter: TAKE PHOTO CALLED
flutter: ==> hastakePhoto : Instance of 'Future<bool>' | path : /var/mobile/Containers/Data/Application/531C4AAB-D429-4530-9BED-72120E229FE5/Library/Caches/test/1633845578523.jpg
flutter: ==> img.width : 1920 | img.height : 1080

Also, the jpeg quality is not optimal, is there a way to improve it?

## Expected results
Get image with 3840x2160 resolution
## Actual results
Got image with 1920 x 1080
*What you see*

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| Apple | iPad  | 14.7.1  |

</details>

**Comment by g-apparence** [comment]
This should be fixed with the reworked version #150
