### ISSUE TITLE
Crash while recording

### ISSUE THREAD

**Issue by ArslanKhan99** [Apparence-io/camera_awesome#117]
App Stop Working while recording video

here are the logs

** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetWriterInputPixelBufferAdaptor appendPixelBuffer:withPresentationTime:] A pixel buffer cannot be appended when readyForMoreMediaData is NO.'
*** First throw call stack:
(0x1acd54654 0x1aca76bcc 0x1b6fa9ab8 0x1b6fa71b8 0x1b6fac980 0x102b8b40c 0x102b84bb0 0x1b7017ee4 0x1b7017c44 0x1b35eddbc 0x1b360e570 0x1aca1a524 0x1ac9c2e98 0x1ac9d3430 0x1ac9c6770 0x1ac9c7294 0x1ac9d078c 0x1aca6bb74 0x1aca6e740)
libc++abi.dylib: terminating with uncaught exception of type NSException
* thread #38, queue = 'camerawesome.dispatchqueue', stop reason = signal SIGABRT
    frame #0: 0x00000001acb49d88 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1acb49d88 <+8>:  b.lo   0x1acb49da4               ; <+36>
    0x1acb49d8c <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1acb49d90 <+16>: mov    x29, sp
    0x1acb49d94 <+20>: bl     0x1acb28ad0               ; cerror_nocancel
Target 0: (Runner) stopped.
Lost connection to device.

*What you see*

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Apple* | *iPhone X*  | *13.6.1*  |

</details>

**Comment by g-apparence** [comment]
This should be fixed with the reworked version #150
