### ISSUE TITLE
error iOS libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc

### ISSUE THREAD

**Issue by ahmadvicky** [Apparence-io/camera_awesome#128]
I few open camera many time 
and then then apps force close 

libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/usr/lib/libMTLCapture.dylib
terminating with uncaught exception of type std::bad_alloc: std::bad_alloc

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.0.1 21A559 darwin-x64, locale en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

cameraawesome: 3.0.0+1

please help me, what wrong about that?

**Comment by g-apparence** [comment]
with uncaught exception of type std::bad_alloc: std::bad_alloc. It's clearly a memory access error. 
 
This could be so many things that it will be hard to understand without more informations. 
What did you do?  
What is your code?  (maybe you try to start / stop the camera too fast or something else)

**Comment by ahmadvicky** [comment]
yes I have research about that, it because memory already full and from OS kill it. 
and, yes I use start and stop camera very fast,

and I just call it like, 

++
Router.push(
            context,
            CameraV(cameraPick: camerapick,));
++

when I saw memory consumption take double.
what I do for handle this case. 

reduce some code on camera, and I am not allowed user change camera.photo into camera.video
==>> ValueNotifier<CaptureModes> _captureMode = ValueNotifier(CaptureModes.PHOTO);

at this I using device iPhone XR.
on this take memory to, I dunno why.

oh and this only happened because use flutter run --debug,

when I trying use Flutter run --release, still same but not take alot like --debug.

**Comment by g-apparence** [comment]
Always check performance using profile mode and not debug mode.
I close this as it's nothing we can do about it.
