### ISSUE TITLE
Record videos for real-time transmission

### ISSUE THREAD

**Issue by ryuujo1573** [Apparence-io/camera_awesome#129]
## Proposal

*Describe your new feature*

Hi, thank you a lot for your great work and your time for reading this.

How can I record videos for real-time transmission like live-streaming?
* Can I get the raw from camera so that I can use `ffmpeg` or something else to encode (e.g. into h.264)
* Is there any inevitable gap between two video fragments?
* When I got my h.264 fragments of video, and sent them to another device by all means, can I play them continuously without any sensible lag?

I would really appreciate your any advice.

**Comment by g-apparence** [comment]
There's a lot of work before making livestream. 
Now platform messaging is better I think it's doable. But maybe there is already work done on Android / iOS plugins that could help you. 

Did you take a look at this?
https://docs.api.video/docs/apivideo-api-reference

**Comment by ryuujo1573** [comment]
Hi, I have considered the ability that `api.video` offers, 
and however, the case is that I may need real time transmission *locally* 🤔 
This could mean some streams spreading among local devices, which AFAIK is implemented by [NDI.tv](ndi.tv) royally free for use but non-opensource. 

Am I doing something like herding the cats? 😿 

Loves from ameteur

**Comment by g-apparence** [comment]
Sorry for late reply, 
yep this sounds a bit overdesign to use this for local transmission. 
It depends if you want to do this for fun or for a professional project. I think you should start looking how video stream works.

**Comment by ryuujo1573** [comment]
Thanks for your suggestion, and I would be look into WebRTC or ffmpeg-based video stream for possible solutions.
