### ISSUE TITLE
Cant take picture:  PATH not found

### ISSUE THREAD

**Issue by repka3** [Apparence-io/camera_awesome#130]
## Steps to Reproduce
```dart
floatingActionButton: FloatingActionButton(
        onPressed: () async {
          try {
            Directory appDocDir = await getApplicationDocumentsDirectory();
            String appDocPath = appDocDir.path;
            String fullpath = appDocPath + '/myimage.jpg';
            print(fullpath);
            final image = await _pictureController.takePicture(fullpath);
```
.......

*Describe how to reproduce the error*
Just installed following the doc, so added the library to pubspec and put 
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
in manifest.
## Expected results

save the picture?

## Actual results

I can see the live preview but when i press the floating button to save the picture (above code)

I/flutter (21730): /data/user/0/com.example.legomobileapp/app_flutter/myimage.jpg
E/com.apparence.camerawesome.CameraPicture(21730): takePicture : PATH NOT FOUND

What "PATH NOT FOUND" mean in this case? The lib need to save the file, so its obs not existing unless you write the picture.
## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Android* | *JSN-L21*  | *10*  |

</details>

**Comment by g-apparence** [comment]
This is simply you system not letting you access to this path. 
=> app_flutter folder should not exists

Try again with testing if your path exists. 
Path not found comes from the android library trying to save a file where a folder not exists.
