### ISSUE TITLE
Error on Build

### ISSUE THREAD

**Issue by Jayvd** [Apparence-io/camera_awesome#133]
`../../.pub-cache/hosted/pub.dartlang.org/camerawesome-0.3.0+1/lib/camerapreview.dart:146:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Tools/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
../../.pub-cache/hosted/pub.dartlang.org/camerawesome-0.3.0+1/lib/camerapreview.dart:168:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Tools/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);`

Is it possible for the developer to update this awesome plugin please?

**Comment by g-apparence** [comment]
This should be now ok thanks to @dim-apparence work. 
Recreate another issue if you have anything.
