### ISSUE TITLE
Out-of-the-box camera screen

### ISSUE THREAD

**Issue by magnuswikhog** [Apparence-io/camera_awesome#137]
## Proposal

It would be nice if this plugin had a camera screen that could be used out-of-the-box, instead of having to create your own.

**Comment by g-apparence** [comment]
CamerAwesome 1.0.0 is here  #150 

The 1.0.0 version of CamerAwesome let you use a complete UI with 4 lines of code. 
Else you can customize it as you want. 

Let us know what you think 🙏🏻
