### ISSUE TITLE
Example code not updated for null safety

### ISSUE THREAD

**Issue by droidzone** [Apparence-io/camera_awesome#138]
## Steps to Reproduce

Use the provided example, and camerawesome 0.3.3 to build

## Expected results

No errors

## Actual results

`error: The argument type 'Null' can't be assigned to the parameter type 'Size'. (argument_type_not_assignable at [myopipclinic] lib/screens/take_pic_new_screen.dart:39)`

The affected line is the following:
`ValueNotifier<Size> _photoSize = ValueNotifier(null);`

## About your device

Oneplus 9 Pro

Please update the given example to include null safety. It seems the package is updated for null safety, but not the example.

**Comment by g-apparence** [comment]
What a mistake. 😱
We have to fix this! 

thanks for reporting
