### ISSUE TITLE
Example is out of date

### ISSUE THREAD

**Issue by cornfeedhobo** [Apparence-io/camera_awesome#139]
## Steps to Reproduce

Run the example files in debug and watch the log

## Expected results

- not using google.bintray.com
- no stack traces

## Actual results

- using google.bintray.com
- lots of stack traces

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| motorola | moto g  | 9 |

</details>

**Comment by g-apparence** [comment]
duplicate of #138
