### ISSUE TITLE
Camera Preview is zoomed

### ISSUE THREAD

**Issue by igor-yusupov** [Apparence-io/camera_awesome#152]
I made a preview of the camera in full screen, while the image is zoomed, and because of this the photo is not what was intended. how to make the preview image look the same as in the photo?

**Comment by igor-yusupov** [comment]
the same issue: https://github.com/Apparence-io/camera_awesome/issues/95

**Comment by g-apparence** [comment]
We have some issues about this yes. 

We are currently working on 1.0.0 version with that in scope.

**Comment by g-apparence** [comment]
#115

**Comment by g-apparence** [comment]
This should be fixed now. 
You can now select the fit of the preview directly from the builder. 
https://github.com/Apparence-io/camera_awesome/blob/master/docs/getting_started/custom-ui.mdx
See previewFit attribute

Don't hesitate to open another issue if you have trouble with this new option 👌
