### ISSUE TITLE
different result on different IOS device

### ISSUE THREAD

**Issue by azazadev** [Apparence-io/camera_awesome#159]
I run a simple example on different IOS device but result is not the same

```
CameraAwesomeBuilder.awesome(
            availableModes: [CaptureModes.VIDEO],
            sensor: Sensors.FRONT,
            flashMode: CameraFlashes.NONE,
            initialCaptureMode: CaptureModes.VIDEO,
            picturePathBuilder: (captureMode) => _path(captureMode),
            videoPathBuilder: (captureMode) => _path(captureMode),
            onMediaTap: (mediaCapture) {
              OpenFile.open(mediaCapture.filePath);
            },
          )
```
Iphone 6s ( IOS 15.2 )

![iphone6s](https://user-images.githubusercontent.com/68111176/206482150-c182708a-12c9-403b-a22c-d4b9a7421eed.png)

Iphone 11 pro ( IOS 16.0.3 )

![iphone11pro](https://user-images.githubusercontent.com/68111176/206482188-f134783e-958c-43ca-8026-b9a8a69cee61.png)

any idea how we can have full screen like the result on Iphone 6s

**Comment by g-apparence** [comment]
This should now be fixed. 
You can change the preview fit directly from the builder now. 

Closing for now. 
If you have any other issue with this feel free to open another bug.

**Comment by azazadev** [comment]
working fine ! Merci
