### ISSUE TITLE
question about 1.0.0 version

### ISSUE THREAD

**Issue by azazadev** [Apparence-io/camera_awesome#160]
thanks for this great package !!, I have few questions about 1.0 version

- any estimated date for releasing this in pubdev ?
- any plan / estimated date to support Analysis mode for IOS ?
- it's possible to have complete example of custom interface ?

Thanks

**Comment by g-apparence** [comment]
Hi, 
thank you for your kind message. 

- we are finishing some refactoring and some little tweaks about the main interface. 
We planned to release on pub.dev next week. 
 - no but that's one of the first priorities we have. Just we are not all having the expertise with obj C... 
 - you have a complete doc available here. I think you're going to find what you want
 https://docs.page/Apparence-io/camera_awesome

**Comment by g-apparence** [comment]
Documentation is now available on the readme.
I close this issue.
