### ISSUE TITLE
Camera Preview Size of an ID Card

### ISSUE THREAD

**Issue by blakewood84** [Apparence-io/camera_awesome#161]
Hey guys I'd love to use your package but I have a problem with the preview. When I first load the preview like the example:

```dart
Widget buildSizedScreenCamera() {
    return Positioned(
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
      child: Container(
        color: Colors.black,
        child: Center(
          child: Container(
            height: 300,
            width: MediaQuery.of(context).size.width,
            child: CameraAwesome(
              onPermissionsResult: _onPermissionsResult,
              selectDefaultSize: (availableSizes) {
                this._availableSizes = availableSizes;
                return availableSizes[0];
              },
              captureMode: _captureMode,
              photoSize: _photoSize,
              sensor: _sensor,
              fitted: true,
              switchFlashMode: _switchFlash,
              zoom: _zoomNotifier,
              onOrientationChanged: _onOrientationChange,
            ),
          ),
        ),
      ),
    );
```

I fortunately get a preview size that is this shape, which has a taller height and a short width:

<img width="267" alt="Screen Shot 2022-12-10 at 4 45 02 PM" src="https://user-images.githubusercontent.com/60270366/206881172-fd088241-a713-4a33-aeb8-843ede75e322.png">

I'd like it to be this shape, which is wider with a short height:

<img width="435" alt="Screen Shot 2022-12-10 at 4 45 13 PM" src="https://user-images.githubusercontent.com/60270366/206881169-dea6a881-7ec9-474b-b675-55a76b4f14ae.png">

And hopefully to make double sense, the preview size i'm talking about is whatever image the `CameraAwesome` widget is showing me from the camera before taking a picture.

When I wrap the Camera in an `Expanded` this does nothing either to stretch it out. Currently for the project I'm working on I am taking a picture of a photo ID of a customer. The dimensions needed for this are: 3.375" x 2.125" (inches) which might look like `Size(524, 304)`.

Thanks so much for any response.

I test on Android and MacOS

**Comment by g-apparence** [comment]
Yes we have that in mind. 
Currently changing aspect ratio works for taking picture / video. 
We are thinking about another option to stretch the preview. 

If I'm correct you are searching a way to crop the preview with custom values. 

Another possibility now is :
- Did you try to use the custom builder and add an overlay above the preview ? (with just a rectangular hole).

**Comment by blakewood84** [comment]
Hey at @g-apparence , thanks for the response. No I didn't know there was a custom builder, I had not seen this in documentation anywhere. How to I access documentation for this to implement? Thanks so much!

**Comment by g-apparence** [comment]
Here is the link for the documentation
https://docs.page/Apparence-io/camera_awesome/
