### ISSUE TITLE
Tap on preview to focus not working

### ISSUE THREAD

**Issue by munum** [Apparence-io/camera_awesome#173]
## Steps to Reproduce

Run `ai_analysis_faces` and tap on preview screen.

## Expected results

Focus on tapped position.

## Actual results

No focus action is triggered.

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| LG | V30  | Android 9  |

</details>

**Comment by g-apparence** [comment]
I think it is due as this example has a canvas above the preview. 
That's not a bug. 

The canvas has been put in this example only as a demo.

**Comment by munum** [comment]
> I think it is due as this example has a canvas above the preview. That's not a bug.
> 
> The canvas has been put in this example only as a demo.

Is there a way to make focus work even when there's a canvas?

**Comment by apalala-dev** [comment]
Just wrap the content printed above `CameraAwesomeBuilder` with an `IgnorePointer` and you will again have access to the built-in gestures of CamerAwesome:
``` dart
Positioned(
  top: 132,
  bottom: 132,
  left: 0,
  right: 0,
  child: IgnorePointer(
    child: AnimatedBuilder(
        animation: animation,
        builder: (context, widget) {
          return CustomPaint(
            painter: FaceDetectorPainter(
                faces, absoluteImageSize, rotation, animation),
          );
        }),
  ),
)
```

**Comment by munum** [comment]
> Just wrap the content printed above `CameraAwesomeBuilder` with an `IgnorePointer` and you will again have access to the built-in gestures of CamerAwesome:
> 
> ```dart
> Positioned(
>   top: 132,
>   bottom: 132,
>   left: 0,
>   right: 0,
>   child: IgnorePointer(
>     child: AnimatedBuilder(
>         animation: animation,
>         builder: (context, widget) {
>           return CustomPaint(
>             painter: FaceDetectorPainter(
>                 faces, absoluteImageSize, rotation, animation),
>           );
>         }),
>   ),
> )
> ```

Thank you. Would it be a good idea to make a pull request for this?

**Comment by apalala-dev** [comment]
This example is not supposed to be perfect, it's just there to show how one could do this kind of things.
You might do them differently in a real app (splitting logic and UI for instance).

I will still include it in a PR I am working on as it's a small change that does no harm :)
