### ISSUE TITLE
Images are saved with a wrong orientation

### ISSUE THREAD

**Issue by Zazo032** [Apparence-io/camera_awesome#175]
## Steps to Reproduce

1. Open a view with a `custom` preview builder
2. Turn the phone horizontally
3. Take a photo

## Expected results

Result image should be saved with the proper orientation

## Actual results

Image is rotated 90º

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Samsung* | *A21s*  | *12*  |

**Comment by Zazo032** [comment]
This was working fine in the old implementation

**Comment by apalala-dev** [comment]
It should be fixed on `master` now for both pictures and videos.
