### ISSUE TITLE
AwesomeFlashButton has wrong state after switching cameras

### ISSUE THREAD

**Issue by Zazo032** [Apparence-io/camera_awesome#177]
## Steps to Reproduce

1. Open the camera
2. Tap `AwesomeFlashButton` to change flash to `FlashMode.always`
3. Switch camera to front camera
4. Switch back to rear camera

## Expected results

`FlashMode` is `always` and `AwesomeFlashButton` shows the torch icon

## Actual results

`FlashMode` is `always` and `AwesomeFlashButton` shows flash off icon

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Samsung* | *A21s*  | *12*  |

**Comment by apalala-dev** [comment]
This should be fixed on `master` now. Let use know if something else is wrong 👍
