### ISSUE TITLE
Can't install the package as version ^1.0.0 does not exist.

### ISSUE THREAD

**Issue by Snimm** [Apparence-io/camera_awesome#184]
## Steps to Reproduce
In Installation and usage > Add the package in your pubspec.yaml section installation is described as adding camerawesome: ^1.0.0 in dependencies. However when I try this I get the following error
```
Because awecam depends on camerawesome ^1.0.0 which doesn't match any versions, version solving failed.
pub get failed (1; Because awecam depends on camerawesome ^1.0.0 which doesn't match any versions, version solving failed.)
```

## Expected results

I expected the package to be installed. 

## Actual results

Package does not install. It throws an error.

I installed camerawesome by camerawesome: any, it installed successfully.
When I checked the version installed, I found it to be 
```
|-- camerawesome 0.3.3
      |-- flutter...
      '-- rxdart 0.27.7
```
I used 
```
  camerawesome:
    git:
      url: https://github.com/Apparence-io/camera_awesome.git
```
It did not throw any error.
And it got the latest version.
```
|-- camerawesome 1.0.0-rc1+4
|   |-- flutter...
|   '-- rxdart 0.27.7

```

It could simply be false documentation.

**Comment by axblueblader** [comment]
it's false documentation i think, the 1.0.0 is not released yet
