### ISSUE TITLE
Vidéo support

### ISSUE THREAD

**Issue by aytunch** [Apparence-io/camera_awesome#19]
## Proposal

*Describe your new feature*
Video support: are there any work in a pr for this? By the way thanks for this great package. I wish it was an official package by Flutter but I guess they don't have time for camera. I am glad you guys help us here.

**Comment by g-apparence** [comment]
Thank you for your encouragement! That means a lot!
The Video feature is planned. Just need time and some people calling for it.

Can I rename this issue simply Video support? Or is this anything else?

**Comment by aytunch** [comment]
@g-apparence Yes you can rename it:) I hope more people can show their interest on video support here and in twitter pretty soon.

**Comment by jtkeyva** [comment]
+1 on video support! the no need to init is a great touch too!

**Comment by gabdsg** [comment]
+1 for video support

**Comment by danielwalczak** [comment]
Yeah would be great to have support for video, but  in the way that user could decide if he wants to shoot image/video. Most of the plugins api restrict usage to only one option at a time while using camera which is not great UX.

**Comment by AnselmMarie** [comment]
+1 for video support

**Comment by aytunch** [comment]
@g-apparence Hi:)
is this similar to Video support? 
Isn't Video just an Image Stream? 👍 
https://github.com/Apparence-io/camera_awesome/pull/23

**Comment by g-apparence** [comment]
Hi, @aytunch 
no image stream is only to make image pre processing like AI. 
Video support will use Android/iOS recording options to create mp4 or other format.

**Comment by aytunch** [comment]
I understand, so image stream feature is for finding the face, overlaying with a widget, etc.
Thanks for the clarification:)
Can you roughly give an estimate on the Video feature? Is it on your near future plans?
Take care

**Comment by g-apparence** [comment]
That's the next planned feature yes. 
We just have a big client release to work on before ;).

**Comment by jamesdixon** [comment]
@g-apparence exciting!

As everyone else has commented, fantastic work on this project. We hope to make some contributions as well. Cheers.

**Comment by cheasonxie** [comment]
+1 for video support

**Comment by gabdsg** [comment]
@g-apparence There is any update on this?

**Comment by g-apparence** [comment]
Yes, we are currently working on iOS video recording feature… :)

**Comment by gabdsg** [comment]
So excited, can't wait haha

**Comment by istornz** [comment]
Here is the video support for iOS 🎉 (Android will be coming next).

https://github.com/Apparence-io/camera_awesome/pull/52

**Comment by istornz** [comment]
iOS code has been rewrite to be more clear & improve performance in video mode (some bugs was fixed to) :) https://github.com/Apparence-io/camera_awesome/pull/59

**Comment by billbull21** [comment]
so,, it's mean. video recorder isn't still available? because, i just have cloned this plugin and start the example. and then,, i got some error when try to record video. something like,, the MethodChannel has not defined yet.

**Comment by g-apparence** [comment]
The issue is still open because Istornz made it for iOS.
Android is not ready yet. 
As we do this freely, we still needs time to do it.

**Comment by billbull21** [comment]
> The issue is still open because Istornz made it for iOS.
> Android is not ready yet.
> As we do this freely, we still needs time to do it.

okayy,,, thanks for your help. hope all goes well.

**Comment by sgbasaraner** [comment]
Is anyone actively working on the Android part of this feature?

**Comment by jtmuller5** [comment]
Any idea when Android support will be available? This package works perfectly for running ML models on a live camera stream but not being able to record at the same time is kind of inconvenient.

**Comment by g-apparence** [comment]
@jtmuller5 Hi, sorry for late reply. 
I'm currently well busy on Pal / Apparence + a newborn and can't do it myself right now. 
But still, I've this is in my list of "when I have time". 🤞

**Comment by aytunch** [comment]
@g-apparence Congrats on the newborn :D

**Comment by aytunch** [comment]
@g-apparence Hi :)
Is there an estimated date for when Android video support can be ready?

**Comment by g-apparence** [comment]
Video recording now is fully working on the 1.0.0

Hope you guys will love it.
