### ISSUE TITLE
[Crash app] When user deny permissions multiple times the library get this problem

### ISSUE THREAD

**Issue by jamescardona11** [Apparence-io/camera_awesome#22]
## Steps to Reproduce

Deny permissions multiple times

## Expected results

*What it should be*

## Actual results
Crash app
void com.apparence.camerawesome.CameraStateManager.stopCamera() on a null object reference

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Android* | *Xiaomi*  | *Android 10*  |

</details>

**Comment by g-apparence** [comment]
Question is why deny multiple times ? 😭 

Well it's still a bug, will dig into it. Thank you reporting it 👍

**Comment by jamescardona11** [comment]
First congratulations for the cam library.
I want to collaborate with this.

The workflow with produce this problem this:
Open the app, deny the permission, then minimize the app and reopen the app and deny the permission.

**Comment by g-apparence** [comment]
Thank you :) 
That's a real pleasure to help this amazing flutter community. 
I think I see the reason, the stream listening for user answer is certainly killed. 
If you are interested you can try fix it, I can help you (error is on Plugin binding with the stream listening). 
Either I'll take a look.

**Comment by g-apparence** [comment]
This has been fixed by last version
