### ISSUE TITLE
adding image Mask

### ISSUE THREAD

**Issue by X-SLAYER** [Apparence-io/camera_awesome#25]
## add widget top stack camera, Container, Images.png...

nice plugin its could be better if there is a way to add a custom widget something like this

![68747470733a2f2f692e696d6775722e636f6d2f734771644533442e6a7067](https://user-images.githubusercontent.com/22800380/96570317-204ffb00-12c2-11eb-82c9-96e0a2654cfb.jpg)

**Comment by g-apparence** [comment]
Did you try to add one ?
You can use a Stack with CamerAwesome and a CustomPainter. 
You got an imageStream to use AI and you know previewSize and pictureSize. 
I believe you got everything to do this.

**Comment by X-SLAYER** [comment]
yeah ik but i t would be better if this feature is merged to the plugin
I try to add it and make a pl
