### ISSUE TITLE
Can not take second picture on Sony Xperia X

### ISSUE THREAD

**Issue by Max-Might** [Apparence-io/camera_awesome#29]
## Steps to Reproduce

Take a picture, then try to take another picture.

## Expected results

It should be possible to take multiple pictures.

## Actual results

Taking the first picture works ok. When I try to take another picture the `PictureController.takePicture()` call never returns.
Interestingly, if I press the zoom-in button after that the picture is taken.

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Sony* | *Xperia X*  | *Android 8.0*  |

</details>

**Comment by g-apparence** [comment]
Hi,
I'm unable to reproduce it for now.
Took multiple pictures and they are different. Are you sure you don't have forgot to update your new picture path in your page ?
If you have the same picture name on a second photo, you have to delete the old one before. We don't rewrite it.

Let me know if that solve your error.

**Comment by Max-Might** [comment]
For me this happens with the code from the example so there should not be a filename overlap.

Reading the code for the `_handleTakePhoto(final MethodCall call, final Result result)` method in android I think there should be a `result.success(true);` at the end since the lack of it might e a reason for the call not returning on the flutter side. What do you think?

**Comment by g-apparence** [comment]
There is a result sent but in a listener as the photo process takes some steps. (Taking a photo depends on the calibration process then take it).
Take photo code is :
```dart
private void _handleTakePhoto(final MethodCall call, final Result result) {
  if(!call.hasArgument("path")) {
    result.error("PATH_NOT_SET", "a file path must be set", "");
    return;
  }
  String path = call.argument("path");
  try {
    mCameraPicture.takePicture(
            mCameraStateManager.getCameraDevice(),
            path,
            mCameraSetup.getJpegOrientation(),
            createTakePhotoResultListener(result)
    );
  } catch (CameraAccessException e) {
    result.error(e.getMessage(), "cannot open camera", "");
  }
}
```

This is where we send the photo result
```
createTakePhotoResultListener(result)
```

Have you updated to the last version ?

**Comment by g-apparence** [comment]
There is a result sent but in a listener as the photo process takes some steps. (Taking a photo depends on the calibration process then take it).
Take photo code is :

```dart
private void _handleTakePhoto(final MethodCall call, final Result result) {
  if(!call.hasArgument("path")) {
    result.error("PATH_NOT_SET", "a file path must be set", "");
    return;
  }
  String path = call.argument("path");
  try {
    mCameraPicture.takePicture(
            mCameraStateManager.getCameraDevice(),
            path,
            mCameraSetup.getJpegOrientation(),
            createTakePhotoResultListener(result)
    );
  } catch (CameraAccessException e) {
    result.error(e.getMessage(), "cannot open camera", "");
  }
}
```

This is where we send the photo result
```
createTakePhotoResultListener(result)
```

Have you updated to the last version ?

**Comment by Max-Might** [comment]
Yes, I am using the latest code.

I see there are a few error cases in `CameraPicture.takePicture()` where the code just calls `return` without calling `onResultListener.onFailure(...)` first. I do not see any of these error messages but this might be a problem still.

**Comment by g-apparence** [comment]
Yes, the only case I see that is not handled as error is rewriting on same file but I might be wrong.
Flutter side protect most of the pre conditions error case but you are right, we should send these to flutter side too.
Will try to reproduce this with another phones to help you.

**Comment by Max-Might** [comment]
Yep, all three of these might need to call it before returning:

```dart
        if (file.exists()) {
            Log.e(TAG, "takePicture : PATH NOT FOUND");
            return;
        }
        if(size == null) {
            Log.e(TAG, "takePicture : NO SIZE SET");
            return;
        }
        if(mCameraSession.getCaptureSession() == null) {
            Log.e(TAG, "takePicture: mCameraSession.getCaptureSession() is null");
            return;
        }
```

**Comment by Max-Might** [comment]
I found that if I disable autofocus in the constructor of `CameraPicture` like this: `setAutoFocus(false);` the stall does not happen and I can take multiple pictures.

**Comment by g-apparence** [comment]
Oh, this seems to be an error yes.
I’ll be able to reproduce it easily now. Will make a try and make you know.

**Comment by g-apparence** [comment]
I think I found the error. 
To completely unlock the focus I've to add in unlockFocus function
`mPreviewRequestBuilder.set(CaptureRequest.CONTROL_AF_TRIGGER, CaptureRequest.CONTROL_AF_TRIGGER_IDLE);`

It seems that without it, the focus is not completely released

**Comment by g-apparence** [comment]
Found finally how to fix it. Hope this helps you!

**Comment by g-apparence** [comment]
@Max-Might let me know
