### ISSUE TITLE
App crash if set flash java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by felipemarchant** [Apparence-io/camera_awesome#30]
## First

**AWSOME PLUGIN, CONGRATULATION!!!**

## Steps to Reproduce

I ran camera_awsome example found here: https://github.com/Apparence-io/camera_awesome/tree/master/example.

1. I granted permissions.
2. Take photo without flash, Work perfectly!!! 
3. But, if I take photo with flash. _pictureController.takePicture throw Java error java.lang.IllegalStateException: Reply already submitted and app crash/close

## Expected results

Take photo with flash or torch

## Actual results

App crash, android studio say Java error java.lang.IllegalStateException: Reply already submitted

> `E/CameraCaptureSession( 9314): Session 0: Exception while stopping repeating: 
E/CameraCaptureSession( 9314): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
E/CameraCaptureSession( 9314): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2553)
E/CameraCaptureSession( 9314): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1141)
E/CameraCaptureSession( 9314): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:526)
E/CameraCaptureSession( 9314): 	at com.apparence.camerawesome.CameraPreview.dispose(CameraPreview.java:164)
E/CameraCaptureSession( 9314): 	at com.apparence.camerawesome.CameraStateManager.onError(CameraStateManager.java:154)
E/CameraCaptureSession( 9314): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.notifyError(CameraDeviceImpl.java:2042)
E/CameraCaptureSession( 9314): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.lambda$Sm85frAzwGZVMAK-NE_gwckYXVQ(Unknown Source:0)
E/CameraCaptureSession( 9314): 	at android.hardware.camera2.impl.-$$Lambda$CameraDeviceImpl$CameraDeviceCallbacks$Sm85frAzwGZVMAK-NE_gwckYXVQ.accept(Unknown Source:8)
E/CameraCaptureSession( 9314): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:271)
E/CameraCaptureSession( 9314): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:195)
E/CameraCaptureSession( 9314): 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:86)
E/CameraCaptureSession( 9314): 	at android.os.Handler.handleCallback(Handler.java:883)
E/CameraCaptureSession( 9314): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/CameraCaptureSession( 9314): 	at android.os.Looper.loop(Looper.java:237)
E/CameraCaptureSession( 9314): 	at android.app.ActivityThread.main(ActivityThread.java:7860)
E/CameraCaptureSession( 9314): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraCaptureSession( 9314): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/CameraCaptureSession( 9314): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
W/Binder  ( 9314): Caught a RuntimeException from the binder stub implementation.
W/Binder  ( 9314): java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest android.hardware.camera2.impl.CameraDeviceImpl$CaptureCallbackHolder.getRequest(int)' on a null object reference
W/Binder  ( 9314): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureErrorLocked(CameraDeviceImpl.java:2372)
W/Binder  ( 9314): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onDeviceError(CameraDeviceImpl.java:2014)
W/Binder  ( 9314): 	at android.hardware.camera2.ICameraDeviceCallbacks$Stub.onTransact(ICameraDeviceCallbacks.java:139)
W/Binder  ( 9314): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
W/Binder  ( 9314): 	at android.os.Binder.execTransact(Binder.java:994)
I/CameraManagerGlobal( 9314): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client com.apparence.camerawesome_example API Level 2
I/CameraManagerGlobal( 9314): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPEN for client com.apparence.camerawesome_example API Level 2
E/com.apparence.camerawesome.CameraStateManager( 9314): close camera session: failed
D/AndroidRuntime( 9314): Shutting down VM
E/AndroidRuntime( 9314): FATAL EXCEPTION: main
E/AndroidRuntime( 9314): Process: com.apparence.camerawesome_example, PID: 9314
E/AndroidRuntime( 9314): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 9314): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/AndroidRuntime( 9314): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime( 9314): 	at com.apparence.camerawesome.CamerawesomePlugin$1.onOpened(CamerawesomePlugin.java:341)
E/AndroidRuntime( 9314): 	at com.apparence.camerawesome.CameraStateManager.onOpened(CameraStateManager.java:135)
E/AndroidRuntime( 9314): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:150)
E/AndroidRuntime( 9314): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 9314): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 9314): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime( 9314): 	at android.app.ActivityThread.main(ActivityThread.java:7860)
E/AndroidRuntime( 9314): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9314): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 9314): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)`

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Samsung* | *A10*  | *Android 10*  |

</details>

**Comment by g-apparence** [comment]
Hi, thank you for your encouragements. 
I tryed to reproduce it but it seems ok on my phone. 
I've a little idea how it did. Can you tell me if the room was dark or not ? 
I think it's related to autofocus. I'm on it.

**Comment by felipemarchant** [comment]
I took photos in different moments. It's was light, sometimes dark. 
In all cases after showed the flash the app crash.
But, I tryed on Moto G One Fusion (another device) and it's work with flash or not. 
It's seems specific problem in some devices.
Thanks for replying me.

**Comment by g-apparence** [comment]
No problem, Will try to investigate. That's the hard part of Android camera2. Different hardware means different behaviors. 
I think this is related to another bug with autofocus on some devices.

**Comment by g-apparence** [comment]
Hello @felipemarchant ,
can you try version 0.1.2+1 and let me know if that fixes it? 
(Will be available in some minutes)
Thank you!

**Comment by felipemarchant** [comment]
Hello. Sorry, I'm late.
I'll try it.
Thanks!
