### ISSUE TITLE
pinch to zoom

### ISSUE THREAD

**Issue by jamesdixon** [Apparence-io/camera_awesome#33]
Hello! Awesome library. Kudos to your and your team.

Has anyone implemented pinch-to-zoom? I believe the primitives are there but curious if anyone has done it.

Cheers.

**Comment by g-apparence** [comment]
Hey, thank you @jamesdixon 👍 
We love to see our work helps others! 

I didn't try myself, but as Flutter has a complete GestureDetector Widget I think it's doable.

**Comment by jamesdixon** [comment]
Will do! If I get it working, I'll share here for others

**Comment by bdlukaa** [comment]
> Will do! If I get it working, I'll share here for others

Did you get it working already?

**Comment by rohrz4nge** [comment]
Just implemented it myself. Since the zoomNotifier is initialized with 0 we do need to add 1 in order for the multiplication to work. You need a variable, for example named `double _previousScale;` to save the scale from the beginning of the zoom event.
```
    return GestureDetector(
      onScaleStart: (ScaleStartDetails details) {
      _previousScale = _zoomNotifier.value + 1;
      },
    onScaleUpdate: (ScaleUpdateDetails details) {
      double result = _previousScale * (details.scale) - 1;
      if (result < 1 && result > 0) {
        _zoomNotifier.value = result;
      }
      setState(() {});
    },
      child: CameraAwesome(
        zoom: _zoomNotifier,
        ...
      ),
    );```

**Comment by dim-apparence** [comment]
Thanks @rohrz4nge, I added this feature to CamerAwesome :)
