### ISSUE TITLE
[iOS] Image Stream

### ISSUE THREAD

**Issue by bpillon** [Apparence-io/camera_awesome#34]
Hello,

It seems that images stream is not working on iOS (and even rather than it is not implemented). Any chance that it would be implemented soon ?

Thanks.

**Comment by g-apparence** [comment]
Yes, that's in the plan with the video recording. 
👍

**Comment by istornz** [comment]
Hello, I added this feature in this PR https://github.com/Apparence-io/camera_awesome/pull/59 👍
