### ISSUE TITLE
HEVC / H.265 Video Recording

### ISSUE THREAD

**Issue by e1engineer** [Apparence-io/camera_awesome#36]
## Proposal

When video recording is implemented, please support H.265 or HEVC video recording. This would be a great improvement over the H.264 in Flutter's camera plugin.

**Comment by g-apparence** [comment]
Thx for the suggestion. 👍 
Could you elaborate on the advantages of these?

**Comment by emcengineer** [comment]
What H.265 allows is for substantially lower bandwidth costs for those of us building video-intensive flutter apps due to lower file sizes. Hardware decoding support for H.265 is improving. I might be able to help out with this endeavor.

**Comment by g-apparence** [comment]
Thank you for clarifications! This seems good reasons. I add these in notes
