### ISSUE TITLE
插件版本不兼容怎么解决？

### ISSUE THREAD

**Issue by 4677-li** [Apparence-io/camera_awesome#37]
## Steps to Reproduce

*Describe how to reproduce the error*

## Expected results

*What it should be*

## Actual results

*What you see*

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Apple* | *iPhone X*  | *13.6.1*  |

</details>

**Comment by g-apparence** [comment]
Can you rewrite it in english plz ?

**Comment by aytunch** [comment]
@g-apparence Hi:)
It says something like "How to solve the incompatible plug-in version?"
But I don't know what that exactly means :D

**Comment by g-apparence** [comment]
Thank you ^^
But yeah this is still very hard to reproduce... Will let him some days before closing.
