### ISSUE TITLE
[iOS] Camera freeze after using a while

### ISSUE THREAD

**Issue by vimaxwell** [Apparence-io/camera_awesome#45]
## Steps to Reproduce

If I rotate the phone or tap on the camera len for a while, the preview will be freeze. If I restart the app, it works. I think the camera can't adapt new exposure or focus frequently.

## Expected results
The preview doesn't drop or auto restart new when there is a problem.

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Apple* | *iPhone 7*  | *14.2*  |

</details>

**Comment by g-apparence** [comment]
@dim-apparence this is an issue for our iOS master

**Comment by istornz** [comment]
Hello @vimaxwell I'm currently working on the video support for iOS. Seems to be fixed in this future branch (in progress, very instable for now).

**Comment by vimaxwell** [comment]
the bug still exists. but the frequency is smaller
