### ISSUE TITLE
Photo Quality

### ISSUE THREAD

**Issue by marianoarga** [Apparence-io/camera_awesome#48]
## Proposal

It will be nice to have a propery for CameraAwesome that provides a way to set the final image taken quality, like "qualitiy: 70"

**Comment by g-apparence** [comment]
Yes, I was thinking about it. 
The thing is that the image package perfectly makes it. So if we had to do it, I'd suggest using it.
Just wanna minimize external libs call right now to prevent library conflicts.

**Comment by g-apparence** [comment]
I close this as this is not the purpose of camerawesome. 
This package is a camera package and not an image manipulation package. 
Check the dart image package that is really great.
