### ISSUE TITLE
Converting Preview to other Image formats, and a quirk in the example

### ISSUE THREAD

**Issue by ebrightfield** [Apparence-io/camera_awesome#50]
I want to convert from the `List<Uint8List>` given in the the camera preview stream to the `Image` class in the [brendan-duncan/image](https://github.com/brendan-duncan/image) library. I don't have even an inkling of how to begin accomplishing this!

All I know is that:

* The `brendan-duncan` Image class has a constructor that takes width/height parameters, as well as a `Uint8List`. 
* In your example (which, thank you!), you use the last element from the `List<Uint8List>` to pass to the `Image.memory` constructor in the widget tree. 
* The stream you expose for the preview seems to actually provide a `Uint8List`, not a `List<Uint8List>`, despite your example successfully treating it as the latter? This is the "quirk" I was referring to in the title.

**Comment by g-apparence** [comment]
Hi,
as it provides a stream to process images as they arrive this is a Uint8List and not a List<Uint8List>. 
I think you refer to this code :

```dart
StreamBuilder(
        stream: previewStream.bufferTime(Duration(milliseconds: 1500)),
        builder: (context, snapshot) {
           if(!snapshot.hasData && snapshot.data.isNotEmpty)
             return Container();
           List<Uint8List> data = snapshot.data;
           print("...${DateTime.now()} new image received... ${data.last.lengthInBytes} bytes");
           return Image.memory(
             data.last,
             width: 120,
           );
       }
```

The reason we have a List<Uint8List> here is because of ```previewStream.bufferTime(Duration(milliseconds: 1500))```.
As flutter require some time to redraw each image, I added a bufferTime that take all photo during 1500 ms and stack them in a buffer. This is just for demo purpose, showing that we successfully get all images from camera in the stream visually. 
If you remove the bufferTime, you will get a simple Uint8List and no a list. 

Hope this helps.

**Comment by Youdoknowjack** [comment]
Hi,

Thank for you the reply. Yes this helps a bit, but I am still unable to work with the `Uint8List` of bytes and get it to the desired data type, as the preview image data's format and sizing is opaque to me. Without modifying any example code, I made the assumption that it's the default 1920x1080 as specified for Android in your code, but that threw a `RangeError`.

Flutter seems to have no problem doing some low level operations to infer size from the bytes, but I can't seem to figure out how to either do that myself or leverage Flutter code to do it for me. 

So I am still unsure how one can convert `Uint8List` from your `imageStream` to `Image` from [brendan-duncan/image](https://github.com/brendan-duncan/image).

**Comment by Youdoknowjack** [comment]
Just my luck, I post and then solve it!

The solution is to take the `Uint8List` from `imageStream` and pass it directly to `imglib.decodeImage()`, where `imglib` is [brendan-duncan/image](https://github.com/brendan-duncan/image).

**Comment by g-apparence** [comment]
Thank you ^^
Glad you enjoy our lib.
