### ISSUE TITLE
no method error when starting camera

### ISSUE THREAD

**Issue by jamesdixon** [Apparence-io/camera_awesome#55]
## Steps to Reproduce

I just installed version `0.2.0` and made one change to my code that was based off the `0.1.x` example. That change was to add `captureMode`.

Whenever I start the camera, I now see the following error:

![image](https://user-images.githubusercontent.com/110114/101959700-10b6a980-3bc3-11eb-8ee0-43730da33e52.png)

Unfortunately, I'm not seeing any stack trace 🤔 

That said, the camera IS working! I just get the aforementioned error.

Curious if this is something you ran into? I'm trying to pick through the other example to see if there are other changes, but hard to tell :)

## Expected results

No error.

## Actual results

See error above.

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Apple* | *iPhone 12 Pro*  | *14.2.1*  |

</details>

**Comment by istornz** [comment]
Thanks for reporting the issue, I'm currently working on it :)

**Comment by jamesdixon** [comment]
Thank you, @istornz !
