### ISSUE TITLE
 PlatformException(FAILED_TO_CHECK_PERMISSIONS, , NULL_ACTIVITY, null)

### ISSUE THREAD

**Issue by enviro-apps** [Apparence-io/camera_awesome#60]
Hello, my Manifest looks like this on Android but I get a Permission error any ideas?

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.cameratest">

    
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.INTERNET" />
    
     
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="Vote"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>

**Comment by g-apparence** [comment]
Hello,
is that a new project or an old one? 
(if your project use the old android plugin version, you'll have to recreate the android folder)

**Comment by salvatoredimaio** [comment]
I created a new project, but I still have the same problem too: PlatformException (FAILED_TO_CHECK_PERMISSIONS,, NULL_ACTIVITY, null).
Tested on Zenfone4, Android 8.1.0

**Comment by g-apparence** [comment]
Hi, will try this when returning from vacation. 

- Could you post the part of your code running the plugin
- You can also try running example to see if it's working on your phone

**Comment by salvatoredimaio** [comment]
Hi, I ran the example (in debug) but only at the start I always get the same exception (PlatformException (FAILED_TO_CHECK_PERMISSIONS ,, NULL_ACTIVITY, null). If I keep giving run, the camera is working.
In release mode the example is working.

**Comment by g-apparence** [comment]
Hi,
will fix this fast if I can reproduce it.

**Comment by g-apparence** [comment]
Tested on Android 8.1, seems related to Asus.

**Comment by aakashbapna** [comment]
Happens on One Plus 3 as well.

**Comment by g-apparence** [comment]
Ok, thanks reporting this. 
Seems related to old devices, maybe the flutter binding use the old version on older devices.  
I'm investigating.
