### ISSUE TITLE
Disable shutter sound effect in iOS

### ISSUE THREAD

**Issue by stefanodecillis** [Apparence-io/camera_awesome#67]
## Disable the shutter sound

As simple as it sounds, I would like to have the possibility to disable the shutter sound (I discovered this problem on iPad) as I'm taking many pictures at the time. I hope it's something feasible to work in on since I don't know if iOS API gives you this possibility. 

Thank you in advance

**Comment by stefanodecillis** [comment]
It looks like it’s difficult to achieve this proposal. iOS doesn’t give API for security/privacy reasons

**Comment by dim-apparence** [comment]
Hi @stefanodecillis yes it seems to be directly integrated in the camera view ...

**Comment by stefanodecillis** [comment]
Hi @dim-apparence thank you for checking it out! Yeah, I read this behaviour was forced by Apple.
I will close this issue since it's not feasible to achieve it.
