### ISSUE TITLE
Value notifier

### ISSUE THREAD

**Issue by romater0** [Apparence-io/camera_awesome#73]
## Proposal
Change value notifier parameters to just the parameters 
*Describe your new feature*
We all manage our states very differently for the value notifer - typed parameters, would be better to just have the parameters on their own rather.

**Comment by g-apparence** [comment]
I agree but we use it to automatically refresh some of the camera plugins. 
We decided that ValueNotifier was part of flutter so this won't break anything. You can still use provider or bloc... Just camerAwesome handles many things for you by using changeNotifier so you don't have to do some boilerplate code. 
For example: changing flash mode requires some texture refreshing that we hide from you.
