### ISSUE TITLE
nhandled Exception: MissingPluginException(No implementation found for method recordVideo on channel camerawesome

### ISSUE THREAD

**Issue by yslion** [Apparence-io/camera_awesome#78]
When I try to record video on Android system , This err message occurred

E/flutter ( 9545): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method refresh on channel camerawesome)
E/flutter ( 9545): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 9545): <asynchronous suspension>
E/flutter ( 9545): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 9545): #2      CamerawesomePlugin.refresh (package:camerawesome/camerawesome_plugin.dart:180:21)
E/flutter ( 9545): #3      VideoController.recordVideo (package:camerawesome/video_controller.dart:7:24)
E/flutter ( 9545): #4      _MyAppState._recordVideo (package:camerawesome_example/main.dart:258:30)
E/flutter ( 9545): <asynchronous suspension>
E/flutter ( 9545): #5      BottomBarWidget.build.<anonymous closure> (package:camerawesome_example/widgets/bottom_bar.dart:59:50)
E/flutter ( 9545): #6      _CameraButtonState._onTapUp (package:camerawesome_example/widgets/take_photo_button.dart:81:24)
E/flutter ( 9545): #7      TapGestureRecognizer.handleTapUp.<anonymous closure> (package:flutter/src/gestures/tap.dart:596:57)
E/flutter ( 9545): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter ( 9545): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:596:11)
E/flutter ( 9545): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter ( 9545): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter ( 9545): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter ( 9545): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter ( 9545): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 9545): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 9545): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 9545): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 9545): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter ( 9545): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter ( 9545): #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter ( 9545): #21     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter ( 9545): #22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter ( 9545): #23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter ( 9545): #24     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 9545): #25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 9545): #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 9545): #27     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 9545): #28     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

**Comment by dim-apparence** [comment]
Hello, video recording is not yet ready for Android, only iOS is supported for now.
See #19
