### ISSUE TITLE
Camera crashes when exiting and re-entering page

### ISSUE THREAD

**Issue by jarren-meep** [Apparence-io/camera_awesome#81]
When I run the camera the first time, it works fine (takes pictures and stuff and works good).
But after I exit the page by Navigator.push and re-visit it, the camera will crash, 

My code that shows the CameraAwesome widget
```
...
Container(
                            child: CameraAwesome(
                              testMode: false,
                              selectDefaultSize: (List<Size> availableSizes) {
                                print(availableSizes);
                                return Size(640.0, 480.0);
                              },
                              onPermissionsResult: _onPermissionsResult,
                              onCameraStarted: () {},
                              onOrientationChanged: (CameraOrientations newOrientation) {},
                              sensor: _sensor,
                              switchFlashMode: _switchFlash,
                              captureMode: _captureMode,
                              orientation: DeviceOrientation.portraitUp,
                              fitted: false,
                              enableAudio: _enableAudio,
                              photoSize: _photoSize,
                            ),
...
```

![bug](https://user-images.githubusercontent.com/52520178/108651759-71d0f680-74fd-11eb-91dd-9a7733968853.PNG)
When loading up the page a second time, this will appear on vscode when ran in debug mode. ^^

_I suspect it's something related to https://github.com/Apparence-io/camera_awesome/issues/61, because texture was mentioned in the code after init, maybe?? ;D_

**Comment by g-apparence** [comment]
Hello, 
sorry for late reply. Could you post a complete code that reproduces the error?

**Comment by jarren-meep** [comment]
Hey!
Sorry I left this hanging, had other priorities and issues to solve first, and couldn't get to replying to this

I created a small example repo for the problem at hand, [Link is here](https://github.com/jarren-meep/cameratest)

Basically whenever I Navigator.push from Camera page to other page and back to Camera page, the camera just stops working :/
I'm using push here because in my app, I display images that have just been taken to the user, and I'm not sure how to do it with Navigator.pop when it doesn't update state.

Hope you can get to look at it, thanks!

**Comment by jamesdixon** [comment]
@jarren-meep is this on Android, iOS or both?

**Comment by jarren-meep** [comment]
@jamesdixon both

**Comment by g-apparence** [comment]
I think last versions should have fixed this. 
Didn't reproduced it. 
Don't hesitate to open a new issue if that's still true

**Comment by sKY02644** [comment]
E/kor.org( 8404): [SurfaceTexture-0-8404-2] checkAndUpdateEglState: invalid current EGLDisplay
E/flutter ( 8404): [ERROR:flutter/fml/platform/android/jni_util.cc(206)] java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
E/flutter ( 8404): 	at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
E/flutter ( 8404): 	at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:251)
E/flutter ( 8404): 	at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.updateTexImage(SurfaceTextureWrapper.java:69)
E/flutter ( 8404): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 8404): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter ( 8404): 	at android.os.Looper.loopOnce(Looper.java:161)
E/flutter ( 8404): 	at android.os.Looper.loop(Looper.java:288)
E/flutter ( 8404): 	at android.app.ActivityThread.main(ActivityThread.java:8010)
E/flutter ( 8404): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 8404): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
E/flutter ( 8404): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
E/flutter ( 8404): 
F/flutter ( 8404): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1503)] Check failed: fml::jni::CheckException(env). 
F/libc    ( 8404): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 8404 (kor.org), pid 8404 (kor.org)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/a3corexx/a3core:13/TP1A.220624.014/A032FXXS6CXE2:user/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2024-09-29 22:31:04.491982045+0000
Process uptime: 207s
Cmdline: com.org.org
pid: 8404, tid: 8404, name: kor.org>>> com.org.org<<<
uid: 10106
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1503)] Check failed: fml::jni::CheckException(env). '
    r0  00000000  r1  000020d4  r2  00000006  r3  ffafc540
    r4  ffafc550  r5  ffafc538  r6  000020d4  r7  0000016b
    r8  00000000  r9  ffffffff  r10 ffafc540  r11 ffafce58
    ip  000020d4  sp  ffafc520  lr  ec6e539f  pc  ec6e53b2
backtrace:
      #00 pc 000633b2  /apex/com.android.runtime/lib/bionic/libc.so (abort+138) (BuildId: e0f412256d8b017587f5ad39dcac7688)
      #01 pc 019dc101  /data/app/~~OEXOh17G274PcpPMb8YkMw==/com.org.org-CFy-RMFfEyWFlV3otdWRoA==/base.apk!libflutter.so (BuildId: 0e4f95f4cc780ddec40d1d9f060ddcae23c2aa2f)
      
      @g-apparence app still crashes
