### ISSUE TITLE
Black Frames At Beginning Of Each Recording

### ISSUE THREAD

**Issue by jtkeyva** [Apparence-io/camera_awesome#84]
## Steps to Reproduce
Run the Example app (very nice btw) from the package on iOS

*Describe how to reproduce the error*
Simply press record and when it plays back the recording, you will see the first split second is recorded black.

## Expected results
Should just capture video so that when you playback, there is no black frames in the beginning.

*What it should be*
Clean video with no black frames in the captured video
## Actual results
Beginning of video it's black and quickly fades into the actual recording
*What you see*
Black frames for about 300 milliseconds
## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Apple* | *iPhone 12*  | *13.6.1-14.4*  |

</details>

**Comment by istornz** [comment]
Hello thanks for reporting the issue, are you running the example in debug mode ? There is (normally) no issue when running in --release mode or directly launched from Xcode.

Have a nice day,
Thanks

**Comment by calvingit** [comment]
Same issue in official camera package :  https://github.com/flutter/flutter/issues/57831

I find some solutions in stackoverflow: [record-video-with-avassetwriter-first-frames-are-black](https://stackoverflow.com/questions/44135223/record-video-with-avassetwriter-first-frames-are-black)

Maybe you can try.

**Comment by g-apparence** [comment]
This should be fixed with the reworked version #150
