### ISSUE TITLE
Can not take second picture on Sony Xperia XZ1

### ISSUE THREAD

**Issue by zamvar** [Apparence-io/camera_awesome#87]
## Steps to Reproduce

*Trigger takePicture when the camera is not done focusing.

## Expected results

*Will take an unfocused Image

## Actual results

*takePicture will not return a response to the flutter side

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
|Sony |Xperia XZ1  | Android 9.0 |

</details>

i think this is related to #29

**Comment by g-apparence** [comment]
Can you please try this on the last version as this was the main fixed issue.

**Comment by zamvar** [comment]
Hi @g-apparence 

Thank you for your response, i tried it with the latest version it now works , sorry i didnt see  the updated version earlier 
Closing this issue now
