### ISSUE TITLE
Crop or take specific size photo

### ISSUE THREAD

**Issue by netgfx** [Apparence-io/camera_awesome#89]
## Proposal

Is this library able to take a specific size photo or crop post capture?

I'm looking into capturing specific documents photos, with pre-defined sizes.

**Comment by g-apparence** [comment]
For now, we don't manipulate images. 
The lib just provides you an image from your camera that you can manipulate with other libs afterward.

**Comment by jamesdixon** [comment]
@g-apparence then what exactly is the `photoSize` param supposed to do? This is a bit confusing to me as I had thought this would have an effect on the output photo, but it doesn't.
