### ISSUE TITLE
SensorManager output logged to console, even after dispose

### ISSUE THREAD

**Issue by ljuborados** [Apparence-io/camera_awesome#93]
## Steps to Reproduce

Open screen with CameraAwesome.

## Expected results

Nothing spectacular, working camera.

## Actual results

Somewhat working camera and a bunch of   
```
D/SensorManager( 5105): TYPE_LIGHT (5): 377.000000
```  
in the output.

Happens even when you dispose the screen with the camera.
Sign of a leakage?

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *any* | *any*  | *Android*  |

</details>

**Comment by merskip** [comment]
I have the same issue

**Comment by ruslanbadaev** [comment]
I, too

**Comment by g-apparence** [comment]
This should be fixed with the reworked version #150
