### ISSUE TITLE
Take picture takes a long time

### ISSUE THREAD

**Issue by MrEmii** [Apparence-io/camera_awesome#99]
## Steps to Reproduce
When takePicture is called and a loading screen is displayed, the timeout is infinite and returns a console error.

## Expected results
Preview of the photo taken

## Actual results
An infinite timeout and a console error. (The photo is never taken)
`W/System  (23513): A resource failed to call release.
I/BufferQueue(23513): [ImageReader-2560x1440f100m2-23513-0](this:0x7f57a000,id:0,api:0,p:-1,c:-1) ~BufferQueueCore
D/RefBase (23513): RefBase: Explicit destruction, weak count = 0 (in 0x7f57af50)
W/RefBase (23513): CallStack::getCurrentInternal not linked, returning null
W/RefBase (23513): CallStack::logStackInternal not linked
W/dev.chek(23513): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, linking, allowed)
`

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
|   LG     |  LG K50     | *Android 10 4.9.190*  |

</details>

**Comment by g-apparence** [comment]
We just fixed it I'm on the release of a new version. 
It will be available in some minutes
